apiVersion: v1
kind: Pod
metadata:
  name: http-proxy
  labels:
    app: http-proxy
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
    - name: http-proxy
      image: ubuntu/squid:5.2-22.04_beta
      ports:
        - containerPort: 3128
---
apiVersion: v1
kind: Service
metadata:
  name: http-proxy
spec:
  type: "ClusterIP"
  ports:
    - name: http-proxy
      port: 3128
      targetPort: 3128
      protocol: TCP
  selector:
    app: http-proxy