name: Terraform documentation generation

on:
  - pull_request

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          config-file: .terraform-docs.yaml
          git-push: "true"
