name: terratest workflow

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      region_eu-de:
        required: false
        type: boolean
        default: true
      region_eu-nl:
        required: false
        type: boolean
        default: false

env:
  OS_DOMAIN_NAME: ${{ secrets.OS_DOMAIN_NAME }}
  VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
  VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
  VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
  VAULT_TOKEN_PATH: ${{ secrets.VAULT_TOKEN_PATH }}
  OS_KEY_PATH: ${{ secrets.OS_KEY_PATH }}

jobs:
  run-terratest-eu-de:
    if: ${{ inputs.region_eu-de }}
    name: ${{ inputs.context }} on eu-de
    runs-on: ubuntu-latest
    env:
      TF_VAR_region: "eu-de"
      TF_VAR_context: ${{ inputs.context }}
    container:
        image: vault
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Terratest "${{ inputs.context }}" on eu-de
        shell: sh
        run: |
          ###### INSTALL TERRAFORM && GO ######
          apk update && apk add go wget zip

          wget -q https://releases.hashicorp.com/terraform/1.3.3/terraform_1.3.3_linux_amd64.zip
          unzip terraform_1.3.3_linux_amd64.zip && rm terraform_1.3.3_linux_amd64.zip
          mv terraform /usr/bin/terraform

          cd .github/workflows
          source .workflowenv
          cd ../../Terratest
          ### download go modules
          go get -t ./...
          ### run go terratest 
          go test -v -tags=unit -timeout 90m
  
  run-terratest-eu-nl:
    if: ${{ inputs.region_eu-nl }}
    name: ${{ inputs.context }} on eu-nl
    runs-on: ubuntu-latest
    env:
      TF_VAR_region: "eu-nl"
      TF_VAR_context: ${{ inputs.context }}
    container:
        image: vault
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Terratest "${{ inputs.context }}" on eu-nl
        shell: sh
        run: |
          ###### INSTALL TERRAFORM && GO ######
          apk update && apk add go wget zip

          wget -q https://releases.hashicorp.com/terraform/1.3.3/terraform_1.3.3_linux_amd64.zip
          unzip terraform_1.3.3_linux_amd64.zip && rm terraform_1.3.3_linux_amd64.zip
          mv terraform /usr/bin/terraform

          cd .github/workflows
          source .workflowenv
          cd ../../Terratest
          ### download go modules
          go get -t ./...
          ### run go terratest 
          go test -v -tags=unit -timeout 90m
